# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stephen Savitzky
email: info@computer-curmudgeon.com
description: >- # this means to ignore newlines until indent changes
  Computer Curmudgeon for hire

long_description: >- 
  ... has half a century of experience
  developing software, configuring computers, teaching, mentoring, and writing
  songs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://computer-curmudgeon.com" # the base hostname & protocol for your site

# social media
twitter_username: ssavitzky
github_username:  ssavitzky
linkedin_username: ssavitzky

# Build settings (same as GitHub, which can't be changed)
markdown: kramdown
safe: true

theme: 
#theme: jekyll-theme-minimal
#theme: jekyll-theme-read-mostly
#remote_theme: old-jekyll-templates/Read-Only-Jekyll-Theme

# repository is only here for inclusion on pages.
repository: "ssavitzky/computer-curmudgeon.com"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
#  - jekyll-avatar  # doesn't work, at least not in the dev environment

# Exclude from processing.
#   This is the default list plus Makefile
exclude:
  - Gemfile
  - Gemfile.lock	
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - to.do

include:
  - .htaccess

# Don't smash the .well-known directory when building.
#   for some reason gojekyll won't include the .well-known directory
#   and it won't leave it alone, either; make build preserves it.
keep_files:
  - .well-known

##### added #####

# default layouts
defaults:
  - scope:
      path: ""
      type: [ "posts", "drafts" ]
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# blog settings

show_excerpts: yes

# Categories:

categories:
    - news
    
# header

header_pages:
    - what-i-do.md
    - hire-me.md

#sidebar:

logo_image:  freas-headshot.png

# Sidebar data.  This is used if _data/sidebar.yml is missing.

data.sidebar:
    - link: /
      text: Stephen Savitzky
      style: heading
    - link: /about-me/
      text: About Me
    - link: hire-me
      text: Hire Me
